members-only app
JayKowski/authentication pull request #2
Opened 2020-01-31 20:47 UTC by JayKowski

ready for review

2020-02-01 12:50 UTC, wathigo requested changes
### Changes Required 
**Hi @JayKowski  and @Elijahscriptdev  :wave:**  

Great work so far :clap: 
However, the application is not able to remember logged in user after closing the browser.
We need to create a new token every time a user logs in and updated the remember digest attribute.
See the comments for suggestions :point_down: 

**Let's fix this and submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-02-01 12:50 UTC, wathigo commented on app/controllers/application_controller.rb
> +  end
[REQUIRED]
* We need to set the cookies every time the user logs in.
We can just update the `remeber_digest` attribute of the user and set a new token ccokie each time a user logs in.
The method should look similar ti this 
```ruby
def sign_in
  gen_token = User.new_token
  user.update_attribute(:remember_digest, User.encrypted(gen_token)
  cookies.permanent[:gen_token] = gen_token
  current_user = user
end
```

2020-02-01 12:50 UTC, wathigo commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
Let's set cookies to nil each time the user logs out.
We can use a helper method for this that looks similar to.
```ruby
def sign_out
  @current_user = nil
  cookies.delete(:gen_token)
end
```

2020-02-01 12:50 UTC, wathigo commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find(session[:user_id]) if session[:user_id]
To remember a user we can use.
```
User.find_by(remember_digest: User.encrypted(cookies.permanent[:gen_token]))
```

2020-02-01 12:50 UTC, wathigo commented on app/controllers/sessions_controller.rb
> +  end
We need to set a new `gen_token` in the cookies and update `remeber_digest` attribute each time a user logs in.
We can do this by invoking the `sign_in` helper method in the application controller(updated version of `create_token_and_save` in `controllers/application_controller` in our case. each time a user is successfully authenticated.

2020-02-03 12:40 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @JayKowski, @Elijahscriptdev , 👋 You have done a great job in this project 👏 

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">


----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2020-02-03 12:49 UTC, JayKowski commented
Thankyou @imhta 😄😄😄👍👍👍💯💯💯

2020-02-03 19:57 UTC, merged